doctrine:
    dbal:
        default_connection: source
        connections:
            source:
                url: '%env(SOURCE_DB_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            destination:
                url: '%env(DESTINATION_DB_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
    orm:
        default_entity_manager: source
        entity_managers:
            source:
                connection: source
                mappings:
                    Source:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Source'
                        prefix: 'App\Entity\Source'
                        alias: Source
            destination:
                connection: destination
                mappings:
                    Destination:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Destination'
                        prefix: 'App\Entity\Destination'
                        alias: Destination
