version: '3'

networks:
  symfony:
    driver: bridge

services:
  source:
    image: percona:5.7
    ports:
      - "${SOURCE_DB_PORT}:3306"
    expose:
      - ${SOURCE_DB_PORT}
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d:delegated
      - ./etc/source-db:/var/lib/mysql:delegated
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${SOURCE_DB_PASSWORD}
      MYSQL_DATABASE: ${SOURCE_DB_DATABASE}
      MYSQL_USER: ${SOURCE_DB_USERNAME}
      MYSQL_ROOT_HOST: 172.22.0.1
    restart: always
    networks:
        - symfony

  destination:
    image: percona:5.7
    ports:
      - "${DESTINATION_DB_PORT}:3306"
    expose:
      - ${DESTINATION_DB_PORT}
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d:delegated
      - ./etc/destination-db:/var/lib/mysql:delegated
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${DESTINATION_DB_PASSWORD}
      MYSQL_DATABASE: ${DESTINATION_DB_DATABASE}
      MYSQL_USER: ${DESTINATION_DB_USERNAME}
      MYSQL_ROOT_HOST: 172.22.0.1
    restart: always
    networks:
        - symfony

  nginx:
    image: nginx:latest
    working_dir: /var/www/html/public
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE:   "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: fpm
      NGINX_SERVER_ROOT: /var/www/html/public
    ports:
      - "${APP_PORT}:80"
    links:
      - source:${APP_URL}
      - destination:${APP_URL}
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:delegated
      - ./public:/var/www/html/public:delegated
    networks:
        - symfony

  fpm:
    build: ./etc/docker/php-fpm
    env_file: .env
    working_dir: /var/www/html/public
    # environment: 
    #   PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    expose:
      - 9000
    links:
      - source:${APP_URL}
      - destination:${APP_URL}
    volumes:
      - ./etc/php/config.ini:/usr/local/etc/php/conf.d/x-config.ini:delegated
      - ./.:/var/www/html:delegated
    networks:
        - symfony

  memcached:
    image: memcached:1.5.2-alpine
    networks:
        - symfony

  # mailhog:
  #   image: mailhog/mailhog
  #   networks:
  #       - symfony

volumes:
  symfony-db:
